### ISSUE TITLE
Copy thu's-weird-adjustments to schedule-chores

### ISSUE THREAD

**Issue by cheesecakelvr** [RkP17/Smart-scheduling-system-#24]
I cannot personally create a pull request from Thu's weird adjustments because, well it contains some weird adjustments to allow the code to run on my pc that we do not want to push to main. Please copy the changes to the code in ssh.java to schedule-chores  and create a pull request from there. There are changes to the function scheduleCode() and storeProbabilities().

**Comment by fabroon** [comment]
That's fine, no worries. Just made the pull request.
